### ISSUE TITLE
Crash when placing Creative Minecart

### ISSUE THREAD

**Issue by JomerDev** [feldim2425/OC-Minecarts#10]
I just crashed after I placed the creative oc-minecart on a network rail

Crashlog:

`
---- Minecraft Crash Report ----
// Oops.

Time: 01.05.16 15:39
Description: Ticking entity

java.lang.NoSuchMethodError: li.cil.oc.api.driver.Item.createEnvironment(Lnet/minecraft/item/ItemStack;Lli/cil/oc/api/driver/EnvironmentHost;)Lli/cil/oc/api/network/ManagedEnvironment;
    at mods.ocminecart.common.inventory.ComponetInventory.connectComponents(ComponetInventory.java:187)
    at mods.ocminecart.common.minecart.ComputerCart.connectNetwork(ComputerCart.java:365)
    at mods.ocminecart.common.minecart.ComputerCart.func_70071_h_(ComputerCart.java:322)
    at net.minecraft.world.World.func_72866_a(World.java:2070)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
    at net.minecraft.world.World.func_72870_g(World.java:2034)
    at net.minecraft.world.World.func_72939_s(World.java:1887)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

`

**Comment by feldim2425** [comment]
Is this OC 1.6 or OC 1.5 ?

**Comment by JomerDev** [comment]
OC 1.6

**Comment by feldim2425** [comment]
This is wierd. Are you using the OC-Minecarts version for oc1.6?

**Comment by JomerDev** [comment]
_facepalm_ I'm sorry. You can close this
