### ISSUE TITLE
minecarts crash game when placed on any tracks.

### ISSUE THREAD

**Issue by blockgoblin31** [feldim2425/OC-Minecarts#19]
using version 1.7-oc1.5. edit. may just be a bug with my version. the game also crashes when the cart is placed on a normal vanilla track.

**Comment by blockgoblin31** [comment]
crash report
-- Affected level --
Details:
	Level name: coast
	All players: 1 total; [EntityPlayerMP['tukr988'/261, l='coast', x=42.64, y=65.00, z=278.32]]
	Chunk stats: ServerChunkCache: 685 Drop: 0
	Level seed: -4830026605951472755
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (4,64,248), Chunk: (at 4,4,8 in 0,15; contains blocks 0,0,240 to 15,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 67286 game time, 30306 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 100667 (now: false), thunder time: 22179 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1063466592 bytes (1014 MB) / 1690304512 bytes (1612 MB) up to 3008888832 bytes (2869 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3228m -Xms256m -XX:PermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	OpenComputers|Core{1.7.5.1290} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	Railcraft{9.12.2.0} [Railcraft] (Railcraft_1.7.10-9.12.2.0.jar) 
	UCHIJAAAA	CartLivery{0.11.1} [Cart Livery] (CartLivery-1.7.10-0.11.1.jar) 
	UCHIJAAAA	ejectorrail{1.0.1} [Ejector Rail] (EjectorRail-1.0.1.jar) 
	UCHIJAAAA	floatingrails{1.0.0} [Floating Rails] (Floating Rails Beta v1.0.jar) 
	UCHIJAAAA	OpenComputers{1.7.5.1290} [OpenComputers] (OpenComputers-MC1.7.10-1.7.5.1290-universal.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	ocminecart{1.7} [OC-Minecarts] (ocminecart-1.7-oc1.5.jar) 
	UCHIJAAAA	row{1.7.10-5.8-RC7} [Rails of War] (RailsOfWar-1.7.10-5.8-RC7.jar) 
	UCHIJAAAA	StevesCarts{2.0.0.b18} [Steve's Carts 2] (StevesCarts2.0.0.b18.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['tukr988'/261, l='coast', x=42.64, y=65.00, z=278.32]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by PublicVoidUpdate** [comment]
I found a fix! I had the same issue, but if you downgrade your version of OC minecarts you will no longer have this issue. I was struggling with a while with it trying to figure out why it wasn't working but then I just downgraded and it stopped not working
